### ISSUE TITLE
Parse error when parsing coffee-script.js

### ISSUE THREAD

**Issue by brianmhunt** [sebmarkbage/link.js#5]
Hi folks,

This is the first of two parse errors I get with link.js. I will file the other report momentarily. It seems when trying to run `link.js` on [coffee-script](https://raw.github.com/jashkenas/coffee-script/1.4.0/extras/coffee-script.js), I get the following error:

```
/usr/local/lib/node_modules/link/Source/Library/link.js:681
        throw new Error('Unexpected token: ' + token.value + ' at line ' + lineNumbe
              ^
Error: Unexpected token: indexOf at line 8
    at expect (/usr/local/lib/node_modules/link/Source/Library/link.js:681:9)
    at scanParenthesis (/usr/local/lib/node_modules/link/Source/Library/link.js:770:2)
    at scanStatement (/usr/local/lib/node_modules/link/Source/Library/link.js:1129:3)
    at scanStatements (/usr/local/lib/node_modules/link/Source/Library/link.js:1143:3)
    at scanBlock (/usr/local/lib/node_modules/link/Source/Library/link.js:988:2)
    at scanFunction (/usr/local/lib/node_modules/link/Source/Library/link.js:951:2)
    at scanFunctionExpression (/usr/local/lib/node_modules/link/Source/Library/link.js:983:3)
    at scanExpression (/usr/local/lib/node_modules/link/Source/Library/link.js:841:4)
    at scanStatement (/usr/local/lib/node_modules/link/Source/Library/link.js:1137:3)
    at scanStatements (/usr/local/lib/node_modules/link/Source/Library/link.js:1143:3)
```

The [coffee-script](https://github.com/jashkenas/coffee-script) script is used in pretty broad usage, so one would expect it to compile with `link.js`.

Just thought you should know.

Thanks

**Comment by sebmarkbage** [comment]
Fixed by above commit. Thanks for the heads up! Please let me know if you find any more.
