### ISSUE TITLE
Parse error when parsing xregexp

### ISSUE THREAD

**Issue by brianmhunt** [sebmarkbage/link.js#6]
When running `link.js` on [XRegExp 3.0pre](https://raw.github.com/slevithan/xregexp/master/xregexp-all.js), I get the following:

```
/usr/local/lib/node_modules/link/Source/Library/link.js:681
        throw new Error('Unexpected token: ' + token.value + ' at line ' + lineNumbe
              ^
Error: Unexpected token: ) at line 271
    at expect (/usr/local/lib/node_modules/link/Source/Library/link.js:681:9)
    at scanArrayInitializer (/usr/local/lib/node_modules/link/Source/Library/link.js:755:3)
    at scanExpression (/usr/local/lib/node_modules/link/Source/Library/link.js:849:4)
    at scanParenthesis (/usr/local/lib/node_modules/link/Source/Library/link.js:765:3)
    at scanExpression (/usr/local/lib/node_modules/link/Source/Library/link.js:853:4)
    at scanCallExpression (/usr/local/lib/node_modules/link/Source/Library/link.js:796:2)
    at scanIdentifierExpression (/usr/local/lib/node_modules/link/Source/Library/link.js:811:25)
    at scanExpression (/usr/local/lib/node_modules/link/Source/Library/link.js:833:4)
    at scanParenthesis (/usr/local/lib/node_modules/link/Source/Library/link.js:765:3)
    at scanExpression (/usr/local/lib/node_modules/link/Source/Library/link.js:853:4)
```

Being a regular expression library, it's a jungle in there. But it would be wonderful if `link.js` were able to parse it.

Cheers.

**Comment by sebmarkbage** [comment]
Fixed by above commit. Thanks for the heads up! Please let me know if you find any more.
